CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'teacher', 'student')),
  is_active BOOLEAN DEFAULT TRUE,
  last_login TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS academic_years (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year VARCHAR(20) NOT NULL,
  semester VARCHAR(20) NOT NULL CHECK (semester IN ('1', '2', 'Spring', 'Fall')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (year, semester)
);

CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) UNIQUE NOT NULL,
  description TEXT,
  head_teacher_id BIGINT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE,
  phone VARCHAR(20),
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  date_of_birth DATE,
  hire_date DATE,
  qualification VARCHAR(100),
  address TEXT,
  emergency_contact VARCHAR(100),
  emergency_phone VARCHAR(20),
  profile_photo VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  grade VARCHAR(20) NOT NULL,
  section VARCHAR(10),
  academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE SET NULL,
  homeroom_teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
  max_students INT DEFAULT 40,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100),
  phone VARCHAR(20),
  class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL,
  roll_number VARCHAR(20),
  admission_number VARCHAR(50) UNIQUE,
  date_of_birth DATE,
  gender VARCHAR(10) CHECK (gender IN ('Male', 'Female', 'Other')),
  blood_group VARCHAR(5),
  address TEXT,
  parent_guardian_name VARCHAR(100),
  parent_guardian_phone VARCHAR(20),
  parent_guardian_email VARCHAR(100),
  emergency_contact VARCHAR(100),
  emergency_phone VARCHAR(20),
  admission_date DATE,
  profile_photo VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(120),
  email VARCHAR(120),
  phone VARCHAR(30),
  profile_photo VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) UNIQUE NOT NULL,
  description TEXT,
  max_marks INT DEFAULT 100,
  passing_marks INT DEFAULT 40,
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  credit_hours INT DEFAULT 3,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teacher_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (teacher_id, subject_id, class_id, academic_year_id)
);

CREATE TABLE IF NOT EXISTS exam_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  code VARCHAR(20) UNIQUE NOT NULL,
  description TEXT,
  weightage NUMERIC(5, 2) DEFAULT 100.00,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  exam_type_id BIGINT NOT NULL REFERENCES exam_types(id) ON DELETE CASCADE,
  academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE SET NULL,
  marks_obtained NUMERIC(5, 2) NOT NULL,
  max_marks INT NOT NULL,
  grade VARCHAR(5),
  remarks TEXT,
  teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
  exam_date DATE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id, subject_id, academic_year_id)
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_teachers_department ON teachers(department_id);
CREATE INDEX IF NOT EXISTS idx_students_class ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_students_name ON students(last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_teacher_subjects_teacher ON teacher_subjects(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_subjects_class ON teacher_subjects(class_id);
CREATE INDEX IF NOT EXISTS idx_marks_student_subject ON marks(student_id, subject_id, academic_year_id);
CREATE INDEX IF NOT EXISTS idx_course_registrations_student ON course_registrations(student_id);

ALTER TABLE departments
  DROP CONSTRAINT IF EXISTS departments_head_teacher_id_fkey;

ALTER TABLE departments
  ADD CONSTRAINT departments_head_teacher_id_fkey
  FOREIGN KEY (head_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;

INSERT INTO academic_years (year, semester, start_date, end_date, is_active)
VALUES ('2025-2026', 'Spring', '2025-01-01', '2025-06-30', TRUE)
ON CONFLICT (year, semester) DO NOTHING;

INSERT INTO exam_types (name, code, weightage) VALUES
  ('Midterm Exam', 'MIDTERM', 30.00),
  ('Final Exam', 'FINAL', 50.00),
  ('Quiz', 'QUIZ', 10.00),
  ('Assignment', 'ASSIGNMENT', 10.00)
ON CONFLICT (code) DO NOTHING;

INSERT INTO departments (name, code, description) VALUES
  ('Mathematics', 'MATH', 'Mathematics Department'),
  ('Science', 'SCI', 'Science Department'),
  ('Languages', 'LANG', 'Languages Department'),
  ('Social Studies', 'SS', 'Social Studies Department'),
  ('Arts', 'ARTS', 'Arts Department')
ON CONFLICT (code) DO NOTHING;

INSERT INTO users (username, password, role, is_active)
VALUES ('admin', '$2b$10$1hP4LgfdR3Jltcro50ljQ.GAvtzDOUm7Nia7bpVtp7qmD1EMXZjRy', 'admin', TRUE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_profiles (user_id, full_name, email)
SELECT id, 'System Administrator', 'admin@example.com'
FROM users
WHERE username = 'admin'
ON CONFLICT (user_id) DO NOTHING;
